/**
 * Copyright (C) 2019-2025 Ubiqube.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.math.BigDecimal;
import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The result of a cache-flush
 */
@JsonPropertyOrder({
		CacheFlushResult.JSON_PROPERTY_COUNT,
		CacheFlushResult.JSON_PROPERTY_RESULT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class CacheFlushResult {
	public static final String JSON_PROPERTY_COUNT = "count";
	@Nullable
	private BigDecimal count;

	public static final String JSON_PROPERTY_RESULT = "result";
	@Nullable
	private String result;

	public CacheFlushResult() {
	}

	public CacheFlushResult count(@Nullable final BigDecimal count) {

		this.count = count;
		return this;
	}

	/**
	 * Amount of entries flushed
	 *
	 * @return count
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_COUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public BigDecimal getCount() {
		return count;
	}

	@JsonProperty(JSON_PROPERTY_COUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setCount(@Nullable final BigDecimal count) {
		this.count = count;
	}

	public CacheFlushResult result(@Nullable final String result) {

		this.result = result;
		return this;
	}

	/**
	 * A message about the result like \&quot;Flushed cache\&quot;
	 *
	 * @return result
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_RESULT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getResult() {
		return result;
	}

	@JsonProperty(JSON_PROPERTY_RESULT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setResult(@Nullable final String result) {
		this.result = result;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		CacheFlushResult cacheFlushResult = (CacheFlushResult) o;
		return Objects.equals(this.count, cacheFlushResult.count) &&
				Objects.equals(this.result, cacheFlushResult.result);
	}

	@Override
	public int hashCode() {
		return Objects.hash(count, result);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CacheFlushResult {\n");
		sb.append("    count: ").append(toIndentedString(count)).append("\n");
		sb.append("    result: ").append(toIndentedString(result)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
