/**
 * Copyright (C) 2019-2025 Ubiqube.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A comment about an RRSet.
 */
@JsonPropertyOrder({
		Comment.JSON_PROPERTY_CONTENT,
		Comment.JSON_PROPERTY_ACCOUNT,
		Comment.JSON_PROPERTY_MODIFIED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class Comment {
	public static final String JSON_PROPERTY_CONTENT = "content";
	@Nullable
	private String content;

	public static final String JSON_PROPERTY_ACCOUNT = "account";
	@Nullable
	private String account;

	public static final String JSON_PROPERTY_MODIFIED_AT = "modified_at";
	@Nullable
	private Integer modifiedAt;

	public Comment() {
	}

	public Comment content(@Nullable final String content) {

		this.content = content;
		return this;
	}

	/**
	 * The actual comment
	 *
	 * @return content
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContent() {
		return content;
	}

	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setContent(@Nullable final String content) {
		this.content = content;
	}

	public Comment account(@Nullable final String account) {

		this.account = account;
		return this;
	}

	/**
	 * Name of an account that added the comment
	 *
	 * @return account
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ACCOUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getAccount() {
		return account;
	}

	@JsonProperty(JSON_PROPERTY_ACCOUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setAccount(@Nullable final String account) {
		this.account = account;
	}

	public Comment modifiedAt(@Nullable final Integer modifiedAt) {

		this.modifiedAt = modifiedAt;
		return this;
	}

	/**
	 * Timestamp of the last change to the comment
	 *
	 * @return modifiedAt
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_MODIFIED_AT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Integer getModifiedAt() {
		return modifiedAt;
	}

	@JsonProperty(JSON_PROPERTY_MODIFIED_AT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setModifiedAt(@Nullable final Integer modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		Comment comment = (Comment) o;
		return Objects.equals(this.content, comment.content) &&
				Objects.equals(this.account, comment.account) &&
				Objects.equals(this.modifiedAt, comment.modifiedAt);
	}

	@Override
	public int hashCode() {
		return Objects.hash(content, account, modifiedAt);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Comment {\n");
		sb.append("    content: ").append(toIndentedString(content)).append("\n");
		sb.append("    account: ").append(toIndentedString(account)).append("\n");
		sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
