/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import jakarta.annotation.Nonnull;

/**
 * Returned when the server encounters an error, either in client input or
 * internally
 */
@JsonPropertyOrder({
		Error.JSON_PROPERTY_ERROR,
		Error.JSON_PROPERTY_ERRORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class Error {
	public static final String JSON_PROPERTY_ERROR = "error";
	@Nonnull
	private String error;

	public static final String JSON_PROPERTY_ERRORS = "errors";
	@Nullable
	private List<String> errors = new ArrayList<>();

	public Error() {
	}

	public Error error(@Nonnull final String error) {

		this.error = error;
		return this;
	}

	/**
	 * A human readable error message
	 *
	 * @return error
	 */
	@Nonnull
	@JsonProperty(JSON_PROPERTY_ERROR)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public String getError() {
		return error;
	}

	@JsonProperty(JSON_PROPERTY_ERROR)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public void setError(@Nonnull final String error) {
		this.error = error;
	}

	public Error errors(@Nullable final List<String> errors) {

		this.errors = errors;
		return this;
	}

	public Error addErrorsItem(final String errorsItem) {
		if (this.errors == null) {
			this.errors = new ArrayList<>();
		}
		this.errors.add(errorsItem);
		return this;
	}

	/**
	 * Optional array of multiple errors encountered during processing
	 *
	 * @return errors
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ERRORS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getErrors() {
		return errors;
	}

	@JsonProperty(JSON_PROPERTY_ERRORS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setErrors(@Nullable final List<String> errors) {
		this.errors = errors;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		Error error = (Error) o;
		return Objects.equals(this.error, error.error) &&
				Objects.equals(this.errors, error.errors);
	}

	@Override
	public int hashCode() {
		return Objects.hash(error, errors);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Error {\n");
		sb.append("    error: ").append(toIndentedString(error)).append("\n");
		sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
