/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Represents zone metadata
 */
@JsonPropertyOrder({
		Metadata.JSON_PROPERTY_KIND,
		Metadata.JSON_PROPERTY_METADATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class Metadata {
	public static final String JSON_PROPERTY_KIND = "kind";
	@Nullable
	private String kind;

	public static final String JSON_PROPERTY_METADATA = "metadata";
	@Nullable
	private List<String> metadata = new ArrayList<>();

	public Metadata() {
	}

	public Metadata kind(@Nullable final String kind) {

		this.kind = kind;
		return this;
	}

	/**
	 * Name of the metadata
	 *
	 * @return kind
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_KIND)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getKind() {
		return kind;
	}

	@JsonProperty(JSON_PROPERTY_KIND)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setKind(@Nullable final String kind) {
		this.kind = kind;
	}

	public Metadata metadata(@Nullable final List<String> metadata) {

		this.metadata = metadata;
		return this;
	}

	public Metadata addMetadataItem(final String metadataItem) {
		if (this.metadata == null) {
			this.metadata = new ArrayList<>();
		}
		this.metadata.add(metadataItem);
		return this;
	}

	/**
	 * Array with all values for this metadata kind.
	 *
	 * @return metadata
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_METADATA)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getMetadata() {
		return metadata;
	}

	@JsonProperty(JSON_PROPERTY_METADATA)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setMetadata(@Nullable final List<String> metadata) {
		this.metadata = metadata;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		Metadata metadata = (Metadata) o;
		return Objects.equals(this.kind, metadata.kind) &&
				Objects.equals(this.metadata, metadata.metadata);
	}

	@Override
	public int hashCode() {
		return Objects.hash(kind, metadata);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Metadata {\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
