/**
 * Copyright (C) 2019-2025 Ubiqube.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import jakarta.annotation.Nonnull;

/**
 * The RREntry object represents a single record.
 */
@JsonPropertyOrder({
		Record.JSON_PROPERTY_CONTENT,
		Record.JSON_PROPERTY_DISABLED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class Record {
	public static final String JSON_PROPERTY_CONTENT = "content";
	@Nonnull
	private String content;

	public static final String JSON_PROPERTY_DISABLED = "disabled";
	@Nullable
	private Boolean disabled;

	public Record() {
	}

	public Record content(@Nonnull final String content) {

		this.content = content;
		return this;
	}

	/**
	 * The content of this record
	 *
	 * @return content
	 */
	@Nonnull
	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)

	public String getContent() {
		return content;
	}

	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.ALWAYS)
	public void setContent(@Nonnull final String content) {
		this.content = content;
	}

	public Record disabled(@Nullable final Boolean disabled) {

		this.disabled = disabled;
		return this;
	}

	/**
	 * Whether or not this record is disabled. When unset, the record is not
	 * disabled
	 *
	 * @return disabled
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_DISABLED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getDisabled() {
		return disabled;
	}

	@JsonProperty(JSON_PROPERTY_DISABLED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setDisabled(@Nullable final Boolean disabled) {
		this.disabled = disabled;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		Record record = (Record) o;
		return Objects.equals(this.content, record.content) &&
				Objects.equals(this.disabled, record.disabled);
	}

	@Override
	public int hashCode() {
		return Objects.hash(content, disabled);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Record {\n");
		sb.append("    content: ").append(toIndentedString(content)).append("\n");
		sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
