/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SearchResultComment
 */
@JsonPropertyOrder({
		SearchResultComment.JSON_PROPERTY_CONTENT,
		SearchResultComment.JSON_PROPERTY_NAME,
		SearchResultComment.JSON_PROPERTY_OBJECT_TYPE,
		SearchResultComment.JSON_PROPERTY_ZONE_ID,
		SearchResultComment.JSON_PROPERTY_ZONE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class SearchResultComment {
	public static final String JSON_PROPERTY_CONTENT = "content";
	@Nullable
	private String content;

	public static final String JSON_PROPERTY_NAME = "name";
	@Nullable
	private String name;

	public static final String JSON_PROPERTY_OBJECT_TYPE = "object_type";
	@Nullable
	private String objectType;

	public static final String JSON_PROPERTY_ZONE_ID = "zone_id";
	@Nullable
	private String zoneId;

	public static final String JSON_PROPERTY_ZONE = "zone";
	@Nullable
	private String zone;

	public SearchResultComment() {
	}

	public SearchResultComment content(@Nullable final String content) {

		this.content = content;
		return this;
	}

	/**
	 * Get content
	 *
	 * @return content
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getContent() {
		return content;
	}

	@JsonProperty(JSON_PROPERTY_CONTENT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setContent(@Nullable final String content) {
		this.content = content;
	}

	public SearchResultComment name(@Nullable final String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 *
	 * @return name
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getName() {
		return name;
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setName(@Nullable final String name) {
		this.name = name;
	}

	public SearchResultComment objectType(@Nullable final String objectType) {

		this.objectType = objectType;
		return this;
	}

	/**
	 * set to \&quot;comment\&quot;
	 *
	 * @return objectType
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getObjectType() {
		return objectType;
	}

	@JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setObjectType(@Nullable final String objectType) {
		this.objectType = objectType;
	}

	public SearchResultComment zoneId(@Nullable final String zoneId) {

		this.zoneId = zoneId;
		return this;
	}

	/**
	 * Get zoneId
	 *
	 * @return zoneId
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ZONE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getZoneId() {
		return zoneId;
	}

	@JsonProperty(JSON_PROPERTY_ZONE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setZoneId(@Nullable final String zoneId) {
		this.zoneId = zoneId;
	}

	public SearchResultComment zone(@Nullable final String zone) {

		this.zone = zone;
		return this;
	}

	/**
	 * Get zone
	 *
	 * @return zone
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ZONE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getZone() {
		return zone;
	}

	@JsonProperty(JSON_PROPERTY_ZONE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setZone(@Nullable final String zone) {
		this.zone = zone;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		SearchResultComment searchResultComment = (SearchResultComment) o;
		return Objects.equals(this.content, searchResultComment.content) &&
				Objects.equals(this.name, searchResultComment.name) &&
				Objects.equals(this.objectType, searchResultComment.objectType) &&
				Objects.equals(this.zoneId, searchResultComment.zoneId) &&
				Objects.equals(this.zone, searchResultComment.zone);
	}

	@Override
	public int hashCode() {
		return Objects.hash(content, name, objectType, zoneId, zone);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SearchResultComment {\n");
		sb.append("    content: ").append(toIndentedString(content)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
		sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
		sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
