/**
 * Copyright (C) 2019-2025 Ubiqube.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * SearchResultZone
 */
@JsonPropertyOrder({
		SearchResultZone.JSON_PROPERTY_NAME,
		SearchResultZone.JSON_PROPERTY_OBJECT_TYPE,
		SearchResultZone.JSON_PROPERTY_ZONE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class SearchResultZone {
	public static final String JSON_PROPERTY_NAME = "name";
	@Nullable
	private String name;

	public static final String JSON_PROPERTY_OBJECT_TYPE = "object_type";
	@Nullable
	private String objectType;

	public static final String JSON_PROPERTY_ZONE_ID = "zone_id";
	@Nullable
	private String zoneId;

	public SearchResultZone() {
	}

	public SearchResultZone name(@Nullable final String name) {

		this.name = name;
		return this;
	}

	/**
	 * Get name
	 *
	 * @return name
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getName() {
		return name;
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setName(@Nullable final String name) {
		this.name = name;
	}

	public SearchResultZone objectType(@Nullable final String objectType) {

		this.objectType = objectType;
		return this;
	}

	/**
	 * set to \&quot;zone\&quot;
	 *
	 * @return objectType
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getObjectType() {
		return objectType;
	}

	@JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setObjectType(@Nullable final String objectType) {
		this.objectType = objectType;
	}

	public SearchResultZone zoneId(@Nullable final String zoneId) {

		this.zoneId = zoneId;
		return this;
	}

	/**
	 * Get zoneId
	 *
	 * @return zoneId
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ZONE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getZoneId() {
		return zoneId;
	}

	@JsonProperty(JSON_PROPERTY_ZONE_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setZoneId(@Nullable final String zoneId) {
		this.zoneId = zoneId;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		SearchResultZone searchResultZone = (SearchResultZone) o;
		return Objects.equals(this.name, searchResultZone.name) &&
				Objects.equals(this.objectType, searchResultZone.objectType) &&
				Objects.equals(this.zoneId, searchResultZone.zoneId);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, objectType, zoneId);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SearchResultZone {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
		sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
