/**
 * Copyright (C) 2019-2025 Ubiqube.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * A TSIG key that can be used to authenticate NOTIFY, AXFR, and DNSUPDATE
 * queries.
 */
@JsonPropertyOrder({
		TSIGKey.JSON_PROPERTY_NAME,
		TSIGKey.JSON_PROPERTY_ID,
		TSIGKey.JSON_PROPERTY_ALGORITHM,
		TSIGKey.JSON_PROPERTY_KEY,
		TSIGKey.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class TSIGKey {
	public static final String JSON_PROPERTY_NAME = "name";
	@Nullable
	private String name;

	public static final String JSON_PROPERTY_ID = "id";
	@Nullable
	private String id;

	public static final String JSON_PROPERTY_ALGORITHM = "algorithm";
	@Nullable
	private String algorithm;

	public static final String JSON_PROPERTY_KEY = "key";
	@Nullable
	private String key;

	public static final String JSON_PROPERTY_TYPE = "type";
	@Nullable
	private String type;

	public TSIGKey() {
	}

	/**
	 * Constructor with only readonly parameters
	 */
	@JsonCreator
	public TSIGKey(
			@JsonProperty(JSON_PROPERTY_ID) final String id,
			@JsonProperty(JSON_PROPERTY_TYPE) final String type) {
		this();
		this.id = id;
		this.type = type;
	}

	public TSIGKey name(@Nullable final String name) {

		this.name = name;
		return this;
	}

	/**
	 * The name of the key
	 *
	 * @return name
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getName() {
		return name;
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setName(@Nullable final String name) {
		this.name = name;
	}

	/**
	 * The ID for this key, used in the TSIGkey URL endpoint.
	 *
	 * @return id
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getId() {
		return id;
	}

	public TSIGKey algorithm(@Nullable final String algorithm) {

		this.algorithm = algorithm;
		return this;
	}

	/**
	 * The algorithm of the TSIG key
	 *
	 * @return algorithm
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ALGORITHM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getAlgorithm() {
		return algorithm;
	}

	@JsonProperty(JSON_PROPERTY_ALGORITHM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setAlgorithm(@Nullable final String algorithm) {
		this.algorithm = algorithm;
	}

	public TSIGKey key(@Nullable final String key) {

		this.key = key;
		return this;
	}

	/**
	 * The Base64 encoded secret key, empty when listing keys. MAY be empty when
	 * POSTing to have the server generate the key material
	 *
	 * @return key
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_KEY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getKey() {
		return key;
	}

	@JsonProperty(JSON_PROPERTY_KEY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setKey(@Nullable final String key) {
		this.key = key;
	}

	/**
	 * Set to \&quot;TSIGKey\&quot;
	 *
	 * @return type
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getType() {
		return type;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		TSIGKey tsIGKey = (TSIGKey) o;
		return Objects.equals(this.name, tsIGKey.name) &&
				Objects.equals(this.id, tsIGKey.id) &&
				Objects.equals(this.algorithm, tsIGKey.algorithm) &&
				Objects.equals(this.key, tsIGKey.key) &&
				Objects.equals(this.type, tsIGKey.type);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, id, algorithm, key, type);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TSIGKey {\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
		sb.append("    key: ").append(toIndentedString(key)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
