/*
 * PowerDNS Authoritative HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.ubiqube.mano.pdns.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * This represents an authoritative DNS Zone.
 */
@JsonPropertyOrder({
		Zone.JSON_PROPERTY_ID,
		Zone.JSON_PROPERTY_NAME,
		Zone.JSON_PROPERTY_TYPE,
		Zone.JSON_PROPERTY_URL,
		Zone.JSON_PROPERTY_KIND,
		Zone.JSON_PROPERTY_RRSETS,
		Zone.JSON_PROPERTY_SERIAL,
		Zone.JSON_PROPERTY_NOTIFIED_SERIAL,
		Zone.JSON_PROPERTY_EDITED_SERIAL,
		Zone.JSON_PROPERTY_MASTERS,
		Zone.JSON_PROPERTY_DNSSEC,
		Zone.JSON_PROPERTY_NSEC3PARAM,
		Zone.JSON_PROPERTY_NSEC3NARROW,
		Zone.JSON_PROPERTY_PRESIGNED,
		Zone.JSON_PROPERTY_SOA_EDIT,
		Zone.JSON_PROPERTY_SOA_EDIT_API,
		Zone.JSON_PROPERTY_API_RECTIFY,
		Zone.JSON_PROPERTY_ZONE,
		Zone.JSON_PROPERTY_CATALOG,
		Zone.JSON_PROPERTY_ACCOUNT,
		Zone.JSON_PROPERTY_NAMESERVERS,
		Zone.JSON_PROPERTY_MASTER_TSIG_KEY_IDS,
		Zone.JSON_PROPERTY_SLAVE_TSIG_KEY_IDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T10:34:53.990305454+02:00[Europe/Paris]", comments = "Generator version: 7.13.0")
public class Zone {
	public static final String JSON_PROPERTY_ID = "id";
	@Nullable
	private String id;

	public static final String JSON_PROPERTY_NAME = "name";
	@Nullable
	private String name;

	public static final String JSON_PROPERTY_TYPE = "type";
	@Nullable
	private String type;

	public static final String JSON_PROPERTY_URL = "url";
	@Nullable
	private String url;

	/**
	 * Zone kind, one of “Native”, “Master”, “Slave”, “Producer”, “Consumer”
	 */
	public enum KindEnum {
		NATIVE(String.valueOf("Native")),

		MASTER(String.valueOf("Master")),

		SLAVE(String.valueOf("Slave")),

		PRODUCER(String.valueOf("Producer")),

		CONSUMER(String.valueOf("Consumer"));

		private final String value;

		KindEnum(final String value) {
			this.value = value;
		}

		@JsonValue
		public String getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static KindEnum fromValue(final String value) {
			for (KindEnum b : KindEnum.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			throw new IllegalArgumentException("Unexpected value '" + value + "'");
		}
	}

	public static final String JSON_PROPERTY_KIND = "kind";
	@Nullable
	private KindEnum kind;

	public static final String JSON_PROPERTY_RRSETS = "rrsets";
	@Nullable
	private List<RRSet> rrsets = new ArrayList<>();

	public static final String JSON_PROPERTY_SERIAL = "serial";
	@Nullable
	private Integer serial;

	public static final String JSON_PROPERTY_NOTIFIED_SERIAL = "notified_serial";
	@Nullable
	private Integer notifiedSerial;

	public static final String JSON_PROPERTY_EDITED_SERIAL = "edited_serial";
	@Nullable
	private Integer editedSerial;

	public static final String JSON_PROPERTY_MASTERS = "masters";
	@Nullable
	private List<String> masters = new ArrayList<>();

	public static final String JSON_PROPERTY_DNSSEC = "dnssec";
	@Nullable
	private Boolean dnssec;

	public static final String JSON_PROPERTY_NSEC3PARAM = "nsec3param";
	@Nullable
	private String nsec3param;

	public static final String JSON_PROPERTY_NSEC3NARROW = "nsec3narrow";
	@Nullable
	private Boolean nsec3narrow;

	public static final String JSON_PROPERTY_PRESIGNED = "presigned";
	@Nullable
	private Boolean presigned;

	public static final String JSON_PROPERTY_SOA_EDIT = "soa_edit";
	@Nullable
	private String soaEdit;

	public static final String JSON_PROPERTY_SOA_EDIT_API = "soa_edit_api";
	@Nullable
	private String soaEditApi;

	public static final String JSON_PROPERTY_API_RECTIFY = "api_rectify";
	@Nullable
	private Boolean apiRectify;

	public static final String JSON_PROPERTY_ZONE = "zone";
	@Nullable
	private String zone;

	public static final String JSON_PROPERTY_CATALOG = "catalog";
	@Nullable
	private String catalog;

	public static final String JSON_PROPERTY_ACCOUNT = "account";
	@Nullable
	private String account;

	public static final String JSON_PROPERTY_NAMESERVERS = "nameservers";
	@Nullable
	private List<String> nameservers = new ArrayList<>();

	public static final String JSON_PROPERTY_MASTER_TSIG_KEY_IDS = "master_tsig_key_ids";
	@Nullable
	private List<String> masterTsigKeyIds = new ArrayList<>();

	public static final String JSON_PROPERTY_SLAVE_TSIG_KEY_IDS = "slave_tsig_key_ids";
	@Nullable
	private List<String> slaveTsigKeyIds = new ArrayList<>();

	public Zone() {
	}

	public Zone id(@Nullable final String id) {

		this.id = id;
		return this;
	}

	/**
	 * Opaque zone id (string), assigned by the server, should not be interpreted by
	 * the application. Guaranteed to be safe for embedding in URLs.
	 *
	 * @return id
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getId() {
		return id;
	}

	@JsonProperty(JSON_PROPERTY_ID)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setId(@Nullable final String id) {
		this.id = id;
	}

	public Zone name(@Nullable final String name) {

		this.name = name;
		return this;
	}

	/**
	 * Name of the zone (e.g. “example.com.”) MUST have a trailing dot
	 *
	 * @return name
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getName() {
		return name;
	}

	@JsonProperty(JSON_PROPERTY_NAME)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setName(@Nullable final String name) {
		this.name = name;
	}

	public Zone type(@Nullable final String type) {

		this.type = type;
		return this;
	}

	/**
	 * Set to “Zone”
	 *
	 * @return type
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getType() {
		return type;
	}

	@JsonProperty(JSON_PROPERTY_TYPE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setType(@Nullable final String type) {
		this.type = type;
	}

	public Zone url(@Nullable final String url) {

		this.url = url;
		return this;
	}

	/**
	 * API endpoint for this zone
	 *
	 * @return url
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getUrl() {
		return url;
	}

	@JsonProperty(JSON_PROPERTY_URL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setUrl(@Nullable final String url) {
		this.url = url;
	}

	public Zone kind(@Nullable final KindEnum kind) {

		this.kind = kind;
		return this;
	}

	/**
	 * Zone kind, one of “Native”, “Master”, “Slave”, “Producer”, “Consumer”
	 *
	 * @return kind
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_KIND)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public KindEnum getKind() {
		return kind;
	}

	@JsonProperty(JSON_PROPERTY_KIND)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setKind(@Nullable final KindEnum kind) {
		this.kind = kind;
	}

	public Zone rrsets(@Nullable final List<RRSet> rrsets) {

		this.rrsets = rrsets;
		return this;
	}

	public Zone addRrsetsItem(final RRSet rrsetsItem) {
		if (this.rrsets == null) {
			this.rrsets = new ArrayList<>();
		}
		this.rrsets.add(rrsetsItem);
		return this;
	}

	/**
	 * RRSets in this zone (for zones/{zone_id} endpoint only; omitted during GET on
	 * the .../zones list endpoint)
	 *
	 * @return rrsets
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_RRSETS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<RRSet> getRrsets() {
		return rrsets;
	}

	@JsonProperty(JSON_PROPERTY_RRSETS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setRrsets(@Nullable final List<RRSet> rrsets) {
		this.rrsets = rrsets;
	}

	public Zone serial(@Nullable final Integer serial) {

		this.serial = serial;
		return this;
	}

	/**
	 * The SOA serial number
	 *
	 * @return serial
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Integer getSerial() {
		return serial;
	}

	@JsonProperty(JSON_PROPERTY_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setSerial(@Nullable final Integer serial) {
		this.serial = serial;
	}

	public Zone notifiedSerial(@Nullable final Integer notifiedSerial) {

		this.notifiedSerial = notifiedSerial;
		return this;
	}

	/**
	 * The SOA serial notifications have been sent out for
	 *
	 * @return notifiedSerial
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NOTIFIED_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Integer getNotifiedSerial() {
		return notifiedSerial;
	}

	@JsonProperty(JSON_PROPERTY_NOTIFIED_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setNotifiedSerial(@Nullable final Integer notifiedSerial) {
		this.notifiedSerial = notifiedSerial;
	}

	public Zone editedSerial(@Nullable final Integer editedSerial) {

		this.editedSerial = editedSerial;
		return this;
	}

	/**
	 * The SOA serial as seen in query responses. Calculated using the SOA-EDIT
	 * metadata, default-soa-edit and default-soa-edit-signed settings
	 *
	 * @return editedSerial
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_EDITED_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Integer getEditedSerial() {
		return editedSerial;
	}

	@JsonProperty(JSON_PROPERTY_EDITED_SERIAL)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setEditedSerial(@Nullable final Integer editedSerial) {
		this.editedSerial = editedSerial;
	}

	public Zone masters(@Nullable final List<String> masters) {

		this.masters = masters;
		return this;
	}

	public Zone addMastersItem(final String mastersItem) {
		if (this.masters == null) {
			this.masters = new ArrayList<>();
		}
		this.masters.add(mastersItem);
		return this;
	}

	/**
	 * List of IP addresses configured as a master for this zone (“Slave” type zones
	 * only)
	 *
	 * @return masters
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_MASTERS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getMasters() {
		return masters;
	}

	@JsonProperty(JSON_PROPERTY_MASTERS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setMasters(@Nullable final List<String> masters) {
		this.masters = masters;
	}

	public Zone dnssec(@Nullable final Boolean dnssec) {

		this.dnssec = dnssec;
		return this;
	}

	/**
	 * Whether or not this zone is DNSSEC signed (inferred from presigned being true
	 * XOR presence of at least one cryptokey with active being true)
	 *
	 * @return dnssec
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_DNSSEC)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getDnssec() {
		return dnssec;
	}

	@JsonProperty(JSON_PROPERTY_DNSSEC)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setDnssec(@Nullable final Boolean dnssec) {
		this.dnssec = dnssec;
	}

	public Zone nsec3param(@Nullable final String nsec3param) {

		this.nsec3param = nsec3param;
		return this;
	}

	/**
	 * The NSEC3PARAM record
	 *
	 * @return nsec3param
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NSEC3PARAM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getNsec3param() {
		return nsec3param;
	}

	@JsonProperty(JSON_PROPERTY_NSEC3PARAM)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setNsec3param(@Nullable final String nsec3param) {
		this.nsec3param = nsec3param;
	}

	public Zone nsec3narrow(@Nullable final Boolean nsec3narrow) {

		this.nsec3narrow = nsec3narrow;
		return this;
	}

	/**
	 * Whether or not the zone uses NSEC3 narrow
	 *
	 * @return nsec3narrow
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NSEC3NARROW)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getNsec3narrow() {
		return nsec3narrow;
	}

	@JsonProperty(JSON_PROPERTY_NSEC3NARROW)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setNsec3narrow(@Nullable final Boolean nsec3narrow) {
		this.nsec3narrow = nsec3narrow;
	}

	public Zone presigned(@Nullable final Boolean presigned) {

		this.presigned = presigned;
		return this;
	}

	/**
	 * Whether or not the zone is pre-signed
	 *
	 * @return presigned
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_PRESIGNED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getPresigned() {
		return presigned;
	}

	@JsonProperty(JSON_PROPERTY_PRESIGNED)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setPresigned(@Nullable final Boolean presigned) {
		this.presigned = presigned;
	}

	public Zone soaEdit(@Nullable final String soaEdit) {

		this.soaEdit = soaEdit;
		return this;
	}

	/**
	 * The SOA-EDIT metadata item
	 *
	 * @return soaEdit
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_SOA_EDIT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getSoaEdit() {
		return soaEdit;
	}

	@JsonProperty(JSON_PROPERTY_SOA_EDIT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setSoaEdit(@Nullable final String soaEdit) {
		this.soaEdit = soaEdit;
	}

	public Zone soaEditApi(@Nullable final String soaEditApi) {

		this.soaEditApi = soaEditApi;
		return this;
	}

	/**
	 * The SOA-EDIT-API metadata item
	 *
	 * @return soaEditApi
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_SOA_EDIT_API)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getSoaEditApi() {
		return soaEditApi;
	}

	@JsonProperty(JSON_PROPERTY_SOA_EDIT_API)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setSoaEditApi(@Nullable final String soaEditApi) {
		this.soaEditApi = soaEditApi;
	}

	public Zone apiRectify(@Nullable final Boolean apiRectify) {

		this.apiRectify = apiRectify;
		return this;
	}

	/**
	 * Whether or not the zone will be rectified on data changes via the API
	 *
	 * @return apiRectify
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_API_RECTIFY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public Boolean getApiRectify() {
		return apiRectify;
	}

	@JsonProperty(JSON_PROPERTY_API_RECTIFY)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setApiRectify(@Nullable final Boolean apiRectify) {
		this.apiRectify = apiRectify;
	}

	public Zone zone(@Nullable final String zone) {

		this.zone = zone;
		return this;
	}

	/**
	 * MAY contain a BIND-style zone file when creating a zone
	 *
	 * @return zone
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ZONE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getZone() {
		return zone;
	}

	@JsonProperty(JSON_PROPERTY_ZONE)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setZone(@Nullable final String zone) {
		this.zone = zone;
	}

	public Zone catalog(@Nullable final String catalog) {

		this.catalog = catalog;
		return this;
	}

	/**
	 * The catalog this zone is a member of
	 *
	 * @return catalog
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_CATALOG)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getCatalog() {
		return catalog;
	}

	@JsonProperty(JSON_PROPERTY_CATALOG)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setCatalog(@Nullable final String catalog) {
		this.catalog = catalog;
	}

	public Zone account(@Nullable final String account) {

		this.account = account;
		return this;
	}

	/**
	 * MAY be set. Its value is defined by local policy
	 *
	 * @return account
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_ACCOUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public String getAccount() {
		return account;
	}

	@JsonProperty(JSON_PROPERTY_ACCOUNT)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setAccount(@Nullable final String account) {
		this.account = account;
	}

	public Zone nameservers(@Nullable final List<String> nameservers) {

		this.nameservers = nameservers;
		return this;
	}

	public Zone addNameserversItem(final String nameserversItem) {
		if (this.nameservers == null) {
			this.nameservers = new ArrayList<>();
		}
		this.nameservers.add(nameserversItem);
		return this;
	}

	/**
	 * MAY be sent in client bodies during creation, and MUST NOT be sent by the
	 * server. Simple list of strings of nameserver names, including the trailing
	 * dot. Not required for slave zones.
	 *
	 * @return nameservers
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_NAMESERVERS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getNameservers() {
		return nameservers;
	}

	@JsonProperty(JSON_PROPERTY_NAMESERVERS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setNameservers(@Nullable final List<String> nameservers) {
		this.nameservers = nameservers;
	}

	public Zone masterTsigKeyIds(@Nullable final List<String> masterTsigKeyIds) {

		this.masterTsigKeyIds = masterTsigKeyIds;
		return this;
	}

	public Zone addMasterTsigKeyIdsItem(final String masterTsigKeyIdsItem) {
		if (this.masterTsigKeyIds == null) {
			this.masterTsigKeyIds = new ArrayList<>();
		}
		this.masterTsigKeyIds.add(masterTsigKeyIdsItem);
		return this;
	}

	/**
	 * The id of the TSIG keys used for master operation in this zone
	 *
	 * @return masterTsigKeyIds
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_MASTER_TSIG_KEY_IDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getMasterTsigKeyIds() {
		return masterTsigKeyIds;
	}

	@JsonProperty(JSON_PROPERTY_MASTER_TSIG_KEY_IDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setMasterTsigKeyIds(@Nullable final List<String> masterTsigKeyIds) {
		this.masterTsigKeyIds = masterTsigKeyIds;
	}

	public Zone slaveTsigKeyIds(@Nullable final List<String> slaveTsigKeyIds) {

		this.slaveTsigKeyIds = slaveTsigKeyIds;
		return this;
	}

	public Zone addSlaveTsigKeyIdsItem(final String slaveTsigKeyIdsItem) {
		if (this.slaveTsigKeyIds == null) {
			this.slaveTsigKeyIds = new ArrayList<>();
		}
		this.slaveTsigKeyIds.add(slaveTsigKeyIdsItem);
		return this;
	}

	/**
	 * The id of the TSIG keys used for slave operation in this zone
	 *
	 * @return slaveTsigKeyIds
	 */
	@Nullable
	@JsonProperty(JSON_PROPERTY_SLAVE_TSIG_KEY_IDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

	public List<String> getSlaveTsigKeyIds() {
		return slaveTsigKeyIds;
	}

	@JsonProperty(JSON_PROPERTY_SLAVE_TSIG_KEY_IDS)
	@JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
	public void setSlaveTsigKeyIds(@Nullable final List<String> slaveTsigKeyIds) {
		this.slaveTsigKeyIds = slaveTsigKeyIds;
	}

	@Override
	public boolean equals(final Object o) {
		if (this == o) {
			return true;
		}
		if ((o == null) || (getClass() != o.getClass())) {
			return false;
		}
		Zone zone = (Zone) o;
		return Objects.equals(this.id, zone.id) &&
				Objects.equals(this.name, zone.name) &&
				Objects.equals(this.type, zone.type) &&
				Objects.equals(this.url, zone.url) &&
				Objects.equals(this.kind, zone.kind) &&
				Objects.equals(this.rrsets, zone.rrsets) &&
				Objects.equals(this.serial, zone.serial) &&
				Objects.equals(this.notifiedSerial, zone.notifiedSerial) &&
				Objects.equals(this.editedSerial, zone.editedSerial) &&
				Objects.equals(this.masters, zone.masters) &&
				Objects.equals(this.dnssec, zone.dnssec) &&
				Objects.equals(this.nsec3param, zone.nsec3param) &&
				Objects.equals(this.nsec3narrow, zone.nsec3narrow) &&
				Objects.equals(this.presigned, zone.presigned) &&
				Objects.equals(this.soaEdit, zone.soaEdit) &&
				Objects.equals(this.soaEditApi, zone.soaEditApi) &&
				Objects.equals(this.apiRectify, zone.apiRectify) &&
				Objects.equals(this.zone, zone.zone) &&
				Objects.equals(this.catalog, zone.catalog) &&
				Objects.equals(this.account, zone.account) &&
				Objects.equals(this.nameservers, zone.nameservers) &&
				Objects.equals(this.masterTsigKeyIds, zone.masterTsigKeyIds) &&
				Objects.equals(this.slaveTsigKeyIds, zone.slaveTsigKeyIds);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, name, type, url, kind, rrsets, serial, notifiedSerial, editedSerial, masters, dnssec, nsec3param, nsec3narrow, presigned, soaEdit, soaEditApi, apiRectify, zone, catalog, account, nameservers, masterTsigKeyIds, slaveTsigKeyIds);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Zone {\n");
		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    url: ").append(toIndentedString(url)).append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    rrsets: ").append(toIndentedString(rrsets)).append("\n");
		sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
		sb.append("    notifiedSerial: ").append(toIndentedString(notifiedSerial)).append("\n");
		sb.append("    editedSerial: ").append(toIndentedString(editedSerial)).append("\n");
		sb.append("    masters: ").append(toIndentedString(masters)).append("\n");
		sb.append("    dnssec: ").append(toIndentedString(dnssec)).append("\n");
		sb.append("    nsec3param: ").append(toIndentedString(nsec3param)).append("\n");
		sb.append("    nsec3narrow: ").append(toIndentedString(nsec3narrow)).append("\n");
		sb.append("    presigned: ").append(toIndentedString(presigned)).append("\n");
		sb.append("    soaEdit: ").append(toIndentedString(soaEdit)).append("\n");
		sb.append("    soaEditApi: ").append(toIndentedString(soaEditApi)).append("\n");
		sb.append("    apiRectify: ").append(toIndentedString(apiRectify)).append("\n");
		sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
		sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
		sb.append("    account: ").append(toIndentedString(account)).append("\n");
		sb.append("    nameservers: ").append(toIndentedString(nameservers)).append("\n");
		sb.append("    masterTsigKeyIds: ").append(toIndentedString(masterTsigKeyIds)).append("\n");
		sb.append("    slaveTsigKeyIds: ").append(toIndentedString(slaveTsigKeyIds)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(final Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
