debug: true
keycloak:
  realm: mano-realm
  auth-server-url: http://auth.mano.ubiqube.com/auth/
  ssl-required: external
  resource: mano-vnfm
  credentials:
    secret: 50e312ab-9f12-481e-b6a8-c23e0de21628
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    com.ubiqube.etsi.mano.service.rest.ManoLoggingHandler: DEBUG
    com:
      ubiqube:
        etsi: DEBUG
    "[Hibernate Types]": WARN
    ma:
      glasnost:
        orika: INFO
    org:
      apache:
        http:
          wire: INFO
        activemq:
          audit: WARN
      elasticsearch:
        client:
          sniff:
            Sniffer: OFF
      hibernate:
        SQL: INFO
      keycloak: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: INFO
        context: INFO
        http: INFO
        jms: INFO
        security: INFO
        web:
          filter: INFO
          servlet: INFO
          reactive: INFO

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full

mano:
  contrail:
    endpoint: http://192.168.1.36:8082/
    username: ncroot
    password: ubiqube
  election:
    script-path: /tmp/etsi-mano/election/groovy
  frontend-url: http://mano-nfvo:8100/ubi-etsi-mano/sol003
  repository:
    phys-root: /tmp/etsi-mano/repository
  swagger-o-auth2: http://auth.mano.ubiqube.com/auth/realms/mano-realm/protocol/openid-connect/token
  config:
    type: nfvo

server:
  error:
    whitelabel:
      enabled: false
  port: 8100
  servlet:
    contextPath: /ubi-etsi-mano

spring:
  application:
    name: etsi-mano
  artemis:
    mode: embedded
  boot:
    admin:
      client:
        instance:
          metadata:
            user:
              name: admin
              password: admin
        password: admin
        url: http://monitoring.mano.ubiqube.com/monitoring/
        username: admin
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/etsi-mano-nfvo.h2;MODE=PostgreSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS mec_meo
    username: sa
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 600000
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: NON_NULL
    generator:
      ignore-unknown: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent-output: true
      write-empty-json-arrays: false
  jmx:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
        search:
          backend:
            directory:
              root: /tmp/etsi-mano-nfvo/indexes
            type: lucene
  liquibase:
    enabled: false
  mvc:
    log-request-details: true
  output:
    ansi:
      enabled: always
  quartz:
    jdbc:
      commentPrefix: '" - "'
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 5000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm
          jwk-set-uri: http://auth.mano.ubiqube.com/auth/realms/mano-realm/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

