openapi: "3.0.0"
info:
  version: 1.0.0
  title: MANO DNS api.
  license:
    name: Apache 2.0
servers:
  - url: http://localhost:8120/v1
paths:
  /addHost:
    get:
      summary: List all hosts
      operationId: listHosts
      tags:
        - hosts
      parameters:
        - name: zone
          in: query
          description: Zone to search for hosts.
          required: false
          schema:
            type: string
      responses:
        200:
          description: An paged array of hosts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hosts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a host
      operationId: createHost
      tags:
        - hosts
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /host/{hostId}:
    get:
      summary: Info for a specific host.
      operationId: showHostById
      tags:
        - hosts
      parameters:
        - name: hostId
          in: path
          required: true
          description: The id of the host to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hosts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Host:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Hosts:
      type: array
      items:
        $ref: "#/components/schemas/Host"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string