#debug: true
logging:
  level:
    com:
      ubiqube:
        etsi: DEBUG
    org:
      hibernate:
        SQL: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: WARN
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure: 
        include: '*'
  info:
    git:
      mode: full

spring:
  application:
    name: mano-mon
  artemis:
    mode: native
    broker-url: tcp://mano-artemis:61616
    user: artemis
    password: simetraehcapa
  boot:
    admin:
      client:
        username: admin
        password: admin
        url:
        - http://mano-admin:8081
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://mano-db:5432/mano_em
    username: mano
    password: mano
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true



